import { ArrowRight, Building, House, KeyRound, MapPin } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { depoimentos, empresa, servicos } from "../data/empresa";
import { imoveis, imoveisDestaque } from "../data/imoveis";
import { ImovelCard } from "../components/ImovelCard";

export function Home() {
  const navegar = useNavigate();
  return <>
    <section className="hero"><div className="hero-building" aria-hidden="true"><video className="hero-video" muted playsInline preload="auto" poster="/assets/hero/predio-final.png"><source src="/assets/hero/predio-drone.mp4" type="video/mp4" /></video></div><div className="hero-copy"><div className="eyebrow">Bragança Paulista e região</div><h1>Todo endereço começa com um <em>sonho.</em></h1><p>{empresa.slogan} Há mais de 10 anos conectando pessoas ao lugar ideal.</p><div className="actions"><Link className="button" to="/imoveis">Explorar imóveis <ArrowRight aria-hidden="true" /></Link><Link className="text-link" to="/anuncie">Anunciar imóvel</Link></div></div><div className="hero-progress" aria-hidden="true"><span /></div></section>
    <section className="search-band" aria-labelledby="busca-rapida"><h2 id="busca-rapida">Onde seu próximo capítulo acontece?</h2><form onSubmit={(e) => { e.preventDefault(); navegar("/imoveis"); }}><select aria-label="Finalidade"><option>Comprar</option><option>Alugar</option></select><select aria-label="Tipo do imóvel"><option>Todos os tipos</option><option>Casa</option><option>Apartamento</option><option>Terreno</option></select><input aria-label="Cidade ou bairro" placeholder="Cidade ou bairro" /><button className="button" type="submit">Buscar imóveis</button></form></section>
    <section className="manifesto section"><span className="eyebrow">Entre concreto e desejo</span><p>Não procuramos apenas paredes. Encontramos o cenário onde sua vida pode <span className="dream-word">acontecer.</span></p></section>
    <section className="horizontal-section"><div className="horizontal-intro"><span className="eyebrow">Seleção Melo & Melo</span><h2>Deslize pela nossa seleção.</h2><p>Acompanhe os imóveis. No final, o catálogo inteiro se abre.</p></div><div className="horizontal-viewport"><div className="horizontal-track">{imoveisDestaque.map((i) => <div className="horizontal-card" key={i.codigo}><ImovelCard imovel={i} /></div>)}<div className="catalogue-gateway" aria-hidden="true"><span>Visão completa</span><strong>Abrir todos os imóveis</strong><ArrowRight /></div></div></div><div className="catalogue-expansion" aria-hidden="true"><div className="catalogue-expansion__copy"><span className="eyebrow">Mapa de oportunidades</span><strong>Todos os imóveis.<br />Uma só visão.</strong></div><div className="catalogue-expansion__mosaic">{imoveis.map((i) => <img key={i.codigo} src={i.fotos[0]} alt="" />)}</div></div></section>
    <section className="all-projects" aria-labelledby="todos-imoveis"><div className="all-projects__heading"><span className="eyebrow">Catálogo aberto</span><h2 id="todos-imoveis">Todos os imóveis. Uma visão completa.</h2><p>Depois da seleção lateral, o catálogo se abre por inteiro.</p></div><div className="all-projects__grid">{imoveis.map((i) => <ImovelCard key={i.codigo} imovel={i} />)}</div><Link className="button all-projects__button" to="/imoveis">Explorar catálogo completo <ArrowRight aria-hidden="true" /></Link></section>
    <section className="section services-section"><div className="section-heading reveal"><div><span className="eyebrow">Soluções completas</span><h2>Do primeiro olhar até a chave na mão.</h2></div></div><div className="service-grid">{servicos.map((s, index) => <article className="reveal" key={s}>{index % 3 === 0 ? <House aria-hidden="true" /> : index % 3 === 1 ? <KeyRound aria-hidden="true" /> : <Building aria-hidden="true" />}<h3>{s}</h3></article>)}</div></section>
    <section className="section testimonial-section"><span className="eyebrow reveal">Experiências reais</span><h2 className="reveal">Confiança construída em cada mudança.</h2><div className="testimonial-grid">{depoimentos.slice(0, 3).map((d) => <blockquote className="reveal" key={d.autor}><p>“{d.texto}”</p><footer>{d.autor}<small>{d.data}</small></footer></blockquote>)}</div></section>
    <section className="section final-cta"><MapPin aria-hidden="true" /><h2>Seu próximo lugar pode estar mais perto do que imagina.</h2><Link className="button" to="/imoveis">Começar busca</Link></section>
  </>;
}
